[project]
name = "league-former"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.9",
    "joblib>=1.4.2",
    "numpy>=2.2.3",
    "scikit-learn>=1.6.1",
    "uvicorn>=0.34.0",
]
